### ISSUE TITLE
Bulk connect common sub-parts of Bundles/Records

### ISSUE THREAD

**Issue by apolonic** [chipsalliance/chisel3#661] opened 2017-08-03 13:48 UTC
Consider the following scenario where mix-ins are used to add fields to compose a Bundle:

```scala
trait Common extends Bundle {
  val c0 = Bool()
  val c1 = Bool()
}

trait A extends Bundle with Common {
  val aa = UInt(10.W)
}

trait B extends Bundle with Common /* with Foo with Bar with ... */ {
  val bb = UInt(10.W)
}
```

We can now use these as I/Os for Bundles, especially for BlackBoxes:

```scala
// A BlackBox that has the following I/Os
// c0, c1, aa
class MyBBoxA extends BlackBox {
 val io = IO(Input(new A))
}

// A BlackBox that has the following I/Os
// c0, c1, bb
class MyBBoxB extends BlackBox {
 val io = IO(Output(new B))
}
```

The problem is that with Chisel3 semantics there is no DRY way to connect the common elements:

```scala
class MyTest extends Module {
 val io = IO(new Bundle {})
 val mod1 = Module(new MyBBoxA)
 val mod2 = Module(new MyBBoxB)
 mod1.io <> mod2.io // <-- doesn't work in Chisel3 semantics
 // Non-DRY code, want to avoid
 mod1.io.c0 <> mod2.io.c0
 mod1.io.c1 <> mod2.io.c1
}
```

Using composition doesn't work since it changes the I/Os to c_c0, c_c1, bb:
```scala
class B_bad extends Bundle {
  val c = new Common
  val bb = UInt(10.W)
}
```

**Option 1**: Chisel2-style "unsafe bulk connect". I think we want to avoid that if possible.

**Option 2**:  some sort of "connect as parent" API. I think we can do this in a type-safe way especially if we know the common subtype:

* `a.asRecordView(Common) <> b.asRecordView(Common)`
* `commonConnect(a, b, Common)`??
* `a.commonConnect(b, Common) `??

**Comment by colinschmidt** [comment] 2017-08-03 16:10
Hmm not just I understand your question but why not just do something like
```
class cx extends Bundle {
val a = new ax()
val b = new bx()
}
...
ua.io.a <> io.c.a
ub.io.b <> io.c.b
```

**Comment by apolonic** [comment] 2017-08-04 07:55
It brings the name of io_a_a0 and io_c_a_a0.
The main cause is to integrate other guy's verilog RTL as an class extended of BlackBox. Integration of the top level involves modules of IP and such things, since I can't regular every interface to this naming rule, either I create one more hierarchy to wrap the IP into a new module, or I can use this "just left side bulk connections" function to resolve it.

**Comment by apolonic** [comment] 2017-08-04 09:09
Is there a way to 'virtually' bund more bundles together to a new 'virtual bundle' and then do bulk connetion?

**Comment by apolonic** [comment] 2017-08-04 09:13
Is there a way to traversal all signals in the bundle and do map or connection?

**Comment by jackkoenig** [comment] 2017-10-19 19:33
It looks to me like @apolonic actually wants Chisel2 bulk connection semantics or kind of an "unsafe bulk connect". This could possibly be resolved via a "setName" API or via clever inheritance and "connectAsParent"

**Comment by edwardcwang** [comment] 2018-11-01 21:04
A similar usecase is: two bundles share a common trait which defines some I/Os but there's no way in pure chisel3 semantics to connect the shared trait together.

**Comment by tampler** [comment] 2018-11-17 10:51
I have a solution with abstract types. Let me know if this works for you. If not, I got another idea. 

```scala
abstract trait Common extends Bundle {
  val c0 = Bool()
  val c1 = Bool()

  // Redefine this in derived classes
  type Bus 
}

trait Foo extends Common
trait Bar extends Common


class A extends Bundle with Foo {
  // doesn't work for = UInt (10.W) thou
  type Bus = UInt
}

class B extends Bundle with Bar /* with Foo with Bar with ... */ {
  type bb = UInt
}

// A BlackBox that has the following I/Os
// c0, c1, aa
class MyBBoxA extends BlackBox {
 val io = IO(Input(new A))
}

// A BlackBox that has the following I/Os
// c0, c1, bb
class MyBBoxB extends BlackBox {
 val io = IO(Output(new B))
}

class Mro extends Module {
 val io = IO(new Bundle {})
 val mod1 = Module(new MyBBoxA)
 val mod2 = Module(new MyBBoxB)

 mod1.io <> mod2.io // <-- now compiles

 // Non-DRY code, want to avoid
 mod1.io.c0 <> mod2.io.c0
 mod1.io.c1 <> mod2.io.c1
}

```

**Comment by edwardcwang** [comment] 2018-11-18 06:39
Thanks Boris for looking at this. Unfortunately, this doesn't work for as Chisel only recognizes instances of Chisel types as fields of a Bundle e.g. `val x = UInt(10.W)`, not the types themselves e.g. `val bad = UInt`. We can't use the Chisel types themselves `type t = ...` as fields for a Bundle, so the proposed solution doesn't appear to solve this problem.

**Comment by tampler** [comment] 2018-11-20 10:55
@edwardcwang I was actually able to generate both FIR and Verilog outputs with connected instances  as below: 
FIR:
    mod1.c1 <= mod2.c1 @[Mro.scala 54:10]
    mod1.c0 <= mod2.c0 @[Mro.scala 54:10]
Verilog:
  assign mod1_c1 = mod2_c1; // @[Mro.scala 54:10]
  assign mod1_c0 = mod2_c0; // @[Mro.scala 54:10]

If this doesn't work for you, pls upload your full example so that we could see how to solve your particular issue

**Comment by edwardcwang** [comment] 2018-11-20 17:19
The problem is that the bundle `A` is missing `aa` as a field and bundle `B` is missing `bb` as a field. As I wrote above, `val aa = UInt` does NOT declare a field, and using the proper declaration of `val aa = UInt(10.W)` results in the old bulk connect error since the members of both bundles are not the same.

```verilog
  MyBBoxA mod1 (
    .c1(mod1_c1),
    .c0(mod1_c0)
    // missing .aa(...)
  );
  MyBBoxB mod2 (
    .c1(mod2_c1),
    .c0(mod2_c0)
    // missing .bb(...)
  );
```

See the following snippet of Chisel:

```scala
abstract trait Common extends Bundle {
  val c0 = Bool()
  val c1 = Bool()
  // Redefine this in derived classes
  type Bus 
}
trait Foo extends Common {
  val aa = UInt // <-- changing this to UInt(10.W) declares a proper field but we will then run into the problem described in this issue, just with an extra layer of indirection (Foo and Bar are unnecessary)
}
trait Bar extends Common {
  val bb = UInt
}
class A extends Bundle with Foo {
  type Bus = UInt
}
class B extends Bundle with Bar /* with Foo with Bar with ... */ {
  type Bus = UInt
}

// A BlackBox that has the following I/Os
// c0, c1, aa
class MyBBoxA extends BlackBox {
 val io = IO(Input(new A))
}

// A BlackBox that has the following I/Os
// c0, c1, bb
class MyBBoxB extends BlackBox {
 val io = IO(Output(new B))
}

class Mro extends Module {
 val io = IO(new Bundle {})
 val mod1 = Module(new MyBBoxA)
 val mod2 = Module(new MyBBoxB)

 mod1.io <> mod2.io
 // Non-DRY code, want to avoid
/*
 mod1.io.c0 <> mod2.io.c0
 mod1.io.c1 <> mod2.io.c1
 */
 mod1.io.aa := 5.U
 mod2.io.bb := 6.U
}
```

**Comment by tampler** [comment] 2018-11-20 19:04
@edwardcwang Okay, I see what causes the problem. 

Its part of the core logic. We need to decide whether it is acceptable to bulk connect two records with partially different fields. Currently, its prohibited and hardcoded here: https://github.com/freechipsproject/chisel3/blob/abee251c262c1d60487153b1227aa587dc39a5cf/chiselFrontend/src/main/scala/chisel3/core/BiConnect.scala#L157

It is rather possible to allow partial bulk connections. But that adds complexity to the implementation and especially test cases. It is also a potential source of subtle bugs in RTL.

I do have a workaround, but it's a hack for this problem, rather than a nice language feature. I'd close this issue and push users to plan their signals upfront if they want to scrap the boilerplate.

**Comment by edwardcwang** [comment] 2018-11-20 19:22
Yep, this is exactly what this issue is trying to resolve...

**Comment by azidar** [comment] 2020-10-27 18:53
Could be supported with new connection operators.

**Comment by chrisbaldwin2** [comment] 2021-02-26 15:27
Looks like someone beat me to the punch. Here is a better formatted version of my post

When using the Bundle Assignment, all elements must match between the two objects. What I would really enjoy is a wildcard assignment that allows for bundles to be split and joined, without needing to write out every signal. This helps a ton with managing a datapath where all of the signals can be wrapped in a bundle, then easily passed from one module to the next similar to the Verilog ```(.*)```. 
Additionally the ```.*``` assignment could be done by a syntax like so
```moduel_i.io <*> _```
which could assign the bundle to the variables in the current context.

Currently when assigning two bundles that don't match, you get the following

> [error] chisel3.internal.ChiselException: Connection between left (anon$2(IO io_ctrlDataOut in ControlFile)) and source (anon$2(IO in unelaborated CPUFile)) failed @.memWData: Left Record missing field (memWData).

I think that it would be better to have an explicit operator to prevent users from accidentally missing signals, but it would be nice if people wanted to "live on the edge" and use wildcards to shorten laborious assignments.

**Comment by jackkoenig** [comment] 2022-01-20 05:19
This isn't necessarily fixed in the way everyone wanted, but `.viewAsSuperType` and `DataView` (new in Chisel 3.5.0) more generally enables such connections in a much more elegant way than before. I'm closing this issue and suggest everyone look at the documentation: https://www.chisel-lang.org/chisel3/docs/cookbooks/dataview.html#how-do-i-connect-a-subset-of-bundle-fields.

**Closed by jackkoenig** 2022-01-20 05:19 UTC
